### ISSUE TITLE
Project 2: Twitter Client - Ready for review

### ISSUE THREAD

**Issue by kkanchamreddy** [kkanchamreddy/MyTweetsApp#1]
Basic version of the app is complete. Please review @codepathreview @codepath

Will probably add more features

**Comment by codepathreview** [comment]
:+1: Congrats on completing the required stories and a few optionals as well! Nice work overall.
- Good job on the UI.
- Good to see you were able to format the timestamp cleanly
- Good to see you refreshed the timeline after composing a new tweet
- Nice touch with the character count being displayed while the user composes a tweet
- Nice to see you used a SwipeRefreshLayout library for easy timeline refreshes
- Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out
- Consider adding ActiveAndroid to the Tweet and User. See the [persistence guide](https://github.com/thecodepath/android_guides/wiki/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](https://github.com/thecodepath/android_guides/wiki/ActiveAndroid-Guide) for more details.
- Consider [better organizing your source files](http://guides.codepath.com/android/Organizing-your-Source-Files)

We have provided a detailed [Twitter Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission.
